### ISSUE TITLE
Cascade email changes from skynet-accounts into mysky

### ISSUE THREAD

**Issue by ro-tex** [SkynetLabs/skynet-mysky#174]
## Overview

When a user changes their email from accounts.siasky.net the email will not match what's saved in mysky. We need to figure out how to cascade that change. We might do it by removing the ability to change your email via account.siasky.net or by accepting changes in both directions (essentially issuing a `PUT /user` from mysky to accounts).

The original discussion on Discord: https://discord.com/channels/341359001797132308/347026783750717450/919257565425172490

**Comment by redsolver** [comment]
In my opinion, the best solution to this issue is to not use the email in MySky at all and instead only login using the seed/challenge. The only advantage that using the email for the seed has is that one MySky user can have multiple portal accounts on the same portal, but I don't really see a reason for this.

**Comment by m-cat** [comment]
We are moving away from using emails in MySky. Closing.
